### ISSUE TITLE
Typo on web pages (operators, pipelines)

### ISSUE THREAD

**Issue by gujun720** [towhee-io/towhee-docs#102]
https://towhee.io/pipelines
https://towhee.io/operators

## On both pages

-  "Towhee provides *varies*" should be "Towhee provides **various**".
- “since it is *completly* managed” should be “since it is **completely** managed”

## On page https://towhee.io/pipelines

-  "Managed Pipelines" should be "Out-of-box Pipelines".

## On page https://towhee.io/operators

- "Managed Operators" should be "Pre-defined Operators".
- Below paragraph looks the same as on the Pipelines page, is it right?
  “Towhee provides varies pipelines for the embedding tasks. You can enjoy the stable, well-designed pipeline interface, while no need to bother the inner complexity, since it is completly managed by the Towhee framework.”

**Comment by Tumao727** [comment]
@gujun720  Mentioned typos have been fixed. Please check the updated website.
