### ISSUE TITLE
Towhee installation versions are not uniform

### ISSUE THREAD

**Issue by Tumao727** [towhee-io/towhee-docs#111]
## [Installation doc](https://docs.towhee.io/get-started/install)
<img width="988" alt="install" src="https://user-images.githubusercontent.com/20420181/147799892-ca687320-c3a5-47ac-9077-c0dfb2e4ba16.png">

## [Quick start doc](https://docs.towhee.io/get-started/quick-start)
<img width="1019" alt="quick-start" src="https://user-images.githubusercontent.com/20420181/147799898-f1e4e78a-9bcc-4ee5-acf0-5c65887ae4fb.png">

**Comment by fzliu** [comment]
Fixed via #116.
